COPY public.link (fromtype, fromid, totype, toid) FROM stdin;
diva-localLabel	12	permissionUnit	uu
diva-localLabel	12	recordType	diva-localLabel
diva-localLabel	12	system	divaData
diva-localLabel	12	user	161616
diva-localLabel	12	validationType	diva-localLabel
diva-output	35	permissionUnit	nordiskamuseet
diva-output	35	recordType	diva-output
diva-output	35	system	divaData
diva-output	35	user	161616
diva-output	35	validationType	publication_report
diva-output	39	diva-localLabel	12
diva-output	39	permissionUnit	uu
diva-output	39	recordType	diva-output
diva-output	39	system	divaData
diva-output	39	user	161616
diva-output	39	validationType	publication_other
diva-output	40	diva-localLabel	12
diva-output	40	permissionUnit	uu
diva-output	40	recordType	diva-output
diva-output	40	system	divaData
diva-output	40	user	161616
diva-output	40	validationType	conference_poster
diva-output	41	diva-localLabel	12
diva-output	41	permissionUnit	uu
diva-output	41	recordType	diva-output
diva-output	41	system	divaData
diva-output	41	user	161616
diva-output	41	validationType	publication_book-chapter
diva-output	42	diva-localLabel	12
diva-output	42	permissionUnit	uu
diva-output	42	recordType	diva-output
diva-output	42	system	divaData
diva-output	42	user	161616
diva-output	42	validationType	publication_edited-book
diva-output	44	diva-localLabel	12
diva-output	44	permissionUnit	uu
diva-output	44	recordType	diva-output
diva-output	44	system	divaData
diva-output	44	user	161616
diva-output	44	validationType	publication_journal-article
diva-output	45	diva-localLabel	12
diva-output	45	permissionUnit	uu
diva-output	45	recordType	diva-output
diva-output	45	system	divaData
diva-output	45	user	161616
diva-output	45	validationType	publication_report
